# This workflow will run tests using node and then publish a package to the server when we push to the master branch or merge a PR

name: Yarn Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
  
jobs:
  rsync-deployment:
    runs-on: ubuntu-latest
    steps:
    # steps that are specific to OmicsTIDE
    - name: checkout
      uses: actions/checkout@v2 
    - name: setup node
      uses: actions/setup-node@v2
      with:
          node-version: 18
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    # steps that are not specific to omicsTIDE
    # install the ssh private key to ~/.ssh/github-actions, add the ssh config and the known hosts
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        name: github-actions
        config: ${{ secrets.SSH_CONFIG }} 
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    # in this step you might need to adapt the --exclude options for your application. For a dry run use the -n option.
    - name: Deploy with rsync
      run: rsync -azvn -O --no-perms --exclude='node_modules' --exclude='.yarn' --exclude='src' --exclude='.gitignore' --exclude='README.md' --exclude='.git' --exclude='.github' --exclude='package.json' --exclude='package-lock-json' . ${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_TARGET }}
    - name: Restart service
      run: ssh ${{ secrets.SSH_HOST }} ${{ secrets.UPDATE_COMMAND }}
